# mapping_conf.toml

[pdu_xy_position]
6 = [-82.0, 30.0]
4 = [-26.0, 35.0]
7 = [30.0, 30.0]
1 = [30.0, -26.0]
5 = [30.0, -82.0]
3 = [-26.0, -87.0]
8 = [-82.0, -82.0]
2 = [-82.0, -26.0]

[pdu_rotation]
1 = true
2 = true
3 = true
4 = true
5 = false
6 = true
7 = true
8 = false

[device_chip_to_pdu_matrix]
"195_0" = [1, 3]
"195_1" = [1, 3]
"195_2" = [1, 4]
"195_3" = [1, 4]
"193_0" = [2, 1]
"193_1" = [2, 1]
"193_2" = [2, 2]
"193_3" = [2, 2]
"192_0" = [2, 3]
"192_1" = [2, 3]
"192_2" = [2, 4]
"192_3" = [2, 4]
"192_4" = [3, 1]
"192_5" = [3, 1]
"193_4" = [3, 2]
"193_5" = [3, 2]
"194_4" = [3, 3]
"194_5" = [3, 3]
"194_1" = [1, 1]
"194_2" = [1, 2]
"195_4" = [3, 4]
"195_5" = [3, 4]
"196_0" = [4, 1]
"196_1" = [4, 1]
"196_2" = [4, 2]
"196_3" = [4, 2]
"196_4" = [5, 2]
"196_5" = [5, 2]
"197_0" = [4, 3]
"197_1" = [4, 3]
"197_2" = [4, 4]
"197_3" = [4, 4]
"197_4" = [6, 2]
"197_5" = [6, 2]
"198_0" = [7, 4]
"198_1" = [7, 4]
"198_2" = [8, 4]
"198_3" = [8, 4]