# mapping_conf.toml

[pdu_xy_position]
1 = [-82.0, 30.0]
2 = [-26.0, 35.0]
3 = [30.0, 30.0]
4 = [30.0, -26.0]
5 = [30.0, -82.0]
6 = [-26.0, -87.0]
7 = [-82.0, -82.0]
8 = [-82.0, -26.0]

[pdu_rotation]
1 = true
2 = true
3 = true
4 = true
5 = true
6 = true
7 = true
8 = true

[device_chip_to_pdu_matrix]
"193_0" = [1, 1]
"193_1" = [1, 1]
"193_2" = [1, 2]
"193_3" = [1, 2]
"193_4" = [4, 1]
"193_5" = [4, 1]
"194_0" = [1, 3]
"194_1" = [1, 3]
"194_2" = [1, 4]
"194_3" = [1, 4]
"194_4" = [4, 2]
"194_5" = [4, 2]
"195_0" = [2, 1]
"195_1" = [2, 1]
"195_2" = [2, 2]
"195_3" = [2, 2]
"195_4" = [4, 3]
"195_5" = [4, 3]
"196_0" = [2, 3]
"196_1" = [2, 3]
"196_2" = [2, 4]
"196_3" = [2, 4]
"196_4" = [4, 4]
"196_5" = [4, 4]
"197_0" = [3, 1]
"197_1" = [3, 1]
"197_2" = [3, 2]
"197_3" = [3, 2]
"197_4" = [5, 1]
"197_5" = [5, 1]
"198_0" = [3, 3]
"198_1" = [3, 3]
"198_2" = [3, 4]
"198_3" = [3, 4]
"198_4" = [5, 2]
"198_5" = [5, 2]
"199_0" = [5, 3]
"199_1" = [5, 3]
"199_2" = [5, 4]
"199_3" = [5, 4]
"201_0" = [6, 1]
"201_1" = [6, 1]
"201_2" = [6, 2]
"201_3" = [6, 2]
"201_4" = [8, 1]
"201_5" = [8, 1]
"202_0" = [6, 3]
"202_1" = [6, 3]
"202_2" = [6, 4]
"202_3" = [6, 4]
"202_4" = [8, 2]
"202_5" = [8, 2]
"203_0" = [7, 1]
"203_1" = [7, 1]
"203_2" = [7, 2]
"203_3" = [7, 2]
"203_4" = [8, 3]
"203_5" = [8, 3]
"192_0" = [7, 3]
"192_1" = [7, 3]
"192_2" = [7, 4]
"192_3" = [7, 4]
"192_4" = [8, 4]
"192_5" = [8, 4]